server.port=8009
spring.main.web-application-type=reactive
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

#AuthService
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

#User Service
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**

#Audit Service
spring.cloud.gateway.routes[2].id=audit-service
spring.cloud.gateway.routes[2].uri=lb://audit-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/audit/**,/api/audits/**

#Audit Management Service
spring.cloud.gateway.routes[3].id=audit-management-service
spring.cloud.gateway.routes[3].uri=lb://audit-management-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/audit-management/**

#Citizen Service  (citizens + documents)
spring.cloud.gateway.routes[4].id=citizen-service
spring.cloud.gateway.routes[4].uri=lb://citizen-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/citizens/**,/api/documents/**

#Scheme Service
spring.cloud.gateway.routes[5].id=scheme-service
spring.cloud.gateway.routes[5].uri=lb://scheme-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/schemes/**

#Enrollment Service
spring.cloud.gateway.routes[6].id=enrollment-service
spring.cloud.gateway.routes[6].uri=lb://enrollment-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/enrollments/**

#Claim Service
spring.cloud.gateway.routes[7].id=claim-service
spring.cloud.gateway.routes[7].uri=lb://claim-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/claims/**

#Disbursement Service
spring.cloud.gateway.routes[8].id=disbursement-service
spring.cloud.gateway.routes[8].uri=lb://disbursement-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/disbursement/**

#Payment Service
spring.cloud.gateway.routes[9].id=payment-service
spring.cloud.gateway.routes[9].uri=lb://payment-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/payment/**

#Compliance Service
spring.cloud.gateway.routes[10].id=compliance-service
spring.cloud.gateway.routes[10].uri=lb://compliance-service
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/compliance/**

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,env,beans
management.endpoint.health.show-details=always
management.info.env.enabled=true
