server.port=9090
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#SchemeService
spring.cloud.gateway.server.webmvc.routes[0].id=SCHEME-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://SCHEME-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/schemes/**

#EnrollmentService
spring.cloud.gateway.server.webmvc.routes[1].id=ENROLLMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ENROLLMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/enrollments/**

#ClaimService
spring.cloud.gateway.server.webmvc.routes[2].id=CLAIM-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://CLAIM-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/claims/**
