server.port=8009

# Downstream service URLs
service.auth.url=http://localhost:8081
service.user.url=http://localhost:8082
service.audit.url=http://localhost:8083
service.citizen.url=http://localhost:8084
service.scheme.url=http://localhost:8085
service.enrollment.url=http://localhost:8086
service.claim.url=http://localhost:8087
service.disbursement.url=http://localhost:8088
service.payment.url=http://localhost:8089


# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
# New services added for audit-management and compliance integration
service.audit-management.url=http://localhost:8091
service.compliance.url=http://localhost:8090
