# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/claim_db
spring.datasource.username=root
spring.datasource.password=cognizant
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA / HIBERNATE (THIS FIXES YOUR ERROR)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

##EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
##SERVER
server.port=8083
##CIRCUIT BREAKER RESILIENT4J
resilience4j.circuitbreaker.instances.schemeService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.schemeService.max-wait-duration-in-half-open-state=5s
resilience4j.circuitbreaker.instances.schemeService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.schemeService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.schemeService.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.schemeService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.schemeService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.schemeService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.schemeService.slidingWindowType=COUNT_BASED

## Actuator endpoints for Circuit Breaker
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
